---
title: "genai_healthcare_sim"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(poLCA)
library(dplyr)
library(psych)
library(gtools)
library(dunn.test)
library(nnet)
```

```{r}
set.seed(123)
n <- 280

alpha_stages <- rep(0.5, 18)
alpha_compare <- rep(0.5, 5)
alpha_trespass <- rep(0.5, 3)
alpha_benefits <- rep(0.5, 8)
alpha_risk <- rep(0.5, 9)
alpha_eleven <- rep(0.5, 11)

probs_stages <- rdirichlet(1, alpha_stages)
#### accuracy variables ####
brainstorm_accuracy <- rdirichlet(1, alpha_compare)
review_accuracy <- rdirichlet(1, alpha_compare)
design_accuracy <- rdirichlet(1, alpha_compare)
data_management_accuracy <- rdirichlet(1, alpha_compare)
ethics_accuracy <- rdirichlet(1, alpha_compare)
grant_accuracy <- rdirichlet(1, alpha_compare)
analysis_accuracy <- rdirichlet(1, alpha_compare)
visualisation_accuracy <- rdirichlet(1, alpha_compare)
draft_accuracy <- rdirichlet(1, alpha_compare)
writing_accuracy <- rdirichlet(1, alpha_compare)
editing_accuracy <- rdirichlet(1, alpha_compare)
translation_accuracy <- rdirichlet(1, alpha_compare)
summary_accuracy <- rdirichlet(1, alpha_compare)
admin_accuracy <- rdirichlet(1, alpha_compare)
impact_accuracy <- rdirichlet(1, alpha_compare)
commercilisation_accuracy <- rdirichlet(1, alpha_compare)
other_accuracy <- rdirichlet(1, alpha_compare)

##### usefulness variables#######
brainstorm_useful <- rdirichlet(1, alpha_compare)
review_useful <- rdirichlet(1, alpha_compare)
design_useful <- rdirichlet(1, alpha_compare)
data_management_useful <- rdirichlet(1, alpha_compare)
ethics_useful <- rdirichlet(1, alpha_compare)
grant_useful <- rdirichlet(1, alpha_compare)
analysis_useful <- rdirichlet(1, alpha_compare)
visualisation_useful <- rdirichlet(1, alpha_compare)
draft_useful <- rdirichlet(1, alpha_compare)
writing_useful <- rdirichlet(1, alpha_compare)
editing_useful <- rdirichlet(1, alpha_compare)
translation_useful <- rdirichlet(1, alpha_compare)
summary_useful <- rdirichlet(1, alpha_compare)
admin_useful <- rdirichlet(1, alpha_compare)
impact_useful <- rdirichlet(1, alpha_compare)
commercilisation_useful <- rdirichlet(1, alpha_compare)
other_useful <- rdirichlet(1, alpha_compare)

probs_stages_useful <- rdirichlet(1, alpha_stages)
probs_mental <- rdirichlet(1, alpha_compare)
probs_time <- rdirichlet(1, alpha_compare)
probs_effort <- rdirichlet(1, alpha_compare)
probs_stress <- rdirichlet(1, alpha_compare)
probs_trespass <- rdirichlet(1, alpha_trespass)
probs_trespass_stages <- rdirichlet(1, alpha_stages)

#### trespass accuracy variables ####
brainstorm_trespass_accuracy <- rdirichlet(1, alpha_compare)
review_trespass_accuracy <- rdirichlet(1, alpha_compare)
design_trespass_accuracy <- rdirichlet(1, alpha_compare)
data_management_trespass_accuracy <- rdirichlet(1, alpha_compare)
ethics_trespass_accuracy <- rdirichlet(1, alpha_compare)
grant_trespass_accuracy <- rdirichlet(1, alpha_compare)
analysis_trespass_accuracy <- rdirichlet(1, alpha_compare)
visualisation_trespass_accuracy <- rdirichlet(1, alpha_compare)
draft_trespass_accuracy <- rdirichlet(1, alpha_compare)
writing_trespass_accuracy <- rdirichlet(1, alpha_compare)
editing_trespass_accuracy <- rdirichlet(1, alpha_compare)
translation_trespass_accuracy <- rdirichlet(1, alpha_compare)
summary_trespass_accuracy <- rdirichlet(1, alpha_compare)
admin_trespass_accuracy <- rdirichlet(1, alpha_compare)
impact_trespass_accuracy <- rdirichlet(1, alpha_compare)
commercilisation_trespass_accuracy <- rdirichlet(1, alpha_compare)
other_trespass_accuracy <- rdirichlet(1, alpha_compare)

##### trespass usefulness variables#######
brainstorm_trespass_useful <- rdirichlet(1, alpha_compare)
review_trespass_useful <- rdirichlet(1, alpha_compare)
design_trespass_useful <- rdirichlet(1, alpha_compare)
data_management_trespass_useful <- rdirichlet(1, alpha_compare)
ethics_trespass_useful <- rdirichlet(1, alpha_compare)
grant_trespass_useful <- rdirichlet(1, alpha_compare)
analysis_trespass_useful <- rdirichlet(1, alpha_compare)
visualisation_trespass_useful <- rdirichlet(1, alpha_compare)
draft_trespass_useful <- rdirichlet(1, alpha_compare)
writing_trespass_useful <- rdirichlet(1, alpha_compare)
editing_trespass_useful <- rdirichlet(1, alpha_compare)
translation_trespass_useful <- rdirichlet(1, alpha_compare)
summary_trespass_useful <- rdirichlet(1, alpha_compare)
admin_trespass_useful <- rdirichlet(1, alpha_compare)
impact_trespass_useful <- rdirichlet(1, alpha_compare)
commercilisation_trespass_useful <- rdirichlet(1, alpha_compare)
other_trespass_useful <- rdirichlet(1, alpha_compare)
probs_benefits <- rdirichlet(1, alpha_benefits)
probs_risk <- rdirichlet(1, alpha_risk)

probs_search <- rdirichlet(1, alpha_compare)
probs_method_understand <- rdirichlet(1, alpha_compare)
probs_method_implement <- rdirichlet(1, alpha_compare)
probs_method_troubleshoot <- rdirichlet(1, alpha_compare)
probs_search_likely <- rdirichlet(1, alpha_compare)
probs_method_understand_likely <- rdirichlet(1, alpha_compare)
probs_method_implement_likely <- rdirichlet(1, alpha_compare)
probs_method_troubleshoot_likely <- rdirichlet(1, alpha_compare)

probs_use_learn <- rdirichlet(1, alpha_compare)
probs_use_brainstorm <- rdirichlet(1, alpha_compare) 
probs_use_review <- rdirichlet(1, alpha_compare)
probs_use_analysis <- rdirichlet(1, alpha_compare)
probs_use_write <- rdirichlet(1, alpha_compare)
probs_use_edit <- rdirichlet(1, alpha_compare)

probs_use_learn_likely <- rdirichlet(1, alpha_compare)
probs_use_brainstorm_likely <- rdirichlet(1, alpha_compare) 
probs_use_review_likely <- rdirichlet(1, alpha_compare)
probs_use_analysis_likely <- rdirichlet(1, alpha_compare)
probs_use_write_likely <- rdirichlet(1, alpha_compare)
probs_use_edit_likely <- rdirichlet(1, alpha_compare)

probs_institution <- rdirichlet(1, alpha_trespass)
probs_grant <- rdirichlet(1, alpha_compare)
probs_grant_likely <- rdirichlet(1, alpha_compare)
probs_grant_impact <- rdirichlet(1, alpha_compare)

probs_disclosure <- rdirichlet(1, alpha_eleven)


sim_data <- data.frame(
  prim_field = sample(c("Clinical Medicine",
                        "Biomedical Sciences",
                        "Public Health/Epidemiology",
                        "Health Services and Science Research",
                        "Health Policy/Economics",
                        "Health Psychology/Behavioural Sciences",
                        "Health Informatics/Biostatistics/Health Data Sciences",
                        "Other"), n, replace = TRUE,
                      prob = c(12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5)),
  role = sample(c("Research assistant",
                  "Technician and professional services",
                  "Postgraduate/Doctoral Student/Medical Doctor Training",
                  "Clinical Research",
                  "Early Career",
                  "Mid Career",
                  "Senior",
                  "Leadership"), n, replace = TRUE,
                prob = c(12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5, 12.5)),
  gen_ai_tool = sample(c("ChatGPT",
                          "Claude",
                          "Google Gemini",
                          "Microsoft Copilot",
                          "Grammarly",
                          "Consensus",
                          "Grok",
                          "Perplexity",
                          "Connected Papers",
                          "Elicit",
                          "Deepseek",
                          "Other",
                          "None"), n, replace = TRUE,
                        prob = c(15, 15, 15, 15, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 10, 2.1, 15)),
  use_3_month = sample(c("Never",
                         "Rarely",
                         "Occassionally",
                         "Sometimes",
                         "Often",
                         "Very often"), n, replace = TRUE,
                       prob = c(20, 15, 12.5, 12.5, 20, 20)),
  ############
  stages = sample(1:18, n, replace = TRUE, prob = probs_stages),
brainstorm_accuracy = sample(1:5, n, replace = TRUE, prob = brainstorm_accuracy),
  review_accuracy = sample(1:5, n, replace = TRUE, prob = review_accuracy),
  design_accuracy = sample(1:5, n, replace = TRUE, prob = design_accuracy),
  data_management_accuracy = sample(1:5, n, replace = TRUE, prob = data_management_accuracy),
  ethics_accuracy = sample(1:5, n, replace = TRUE, prob = ethics_accuracy),
  grant_accuracy = sample(1:5, n, replace = TRUE, prob = grant_accuracy),
  analysis_accuracy = sample(1:5, n, replace = TRUE, prob = analysis_accuracy),
  visualisation_accuracy = sample(1:5, n, replace = TRUE, prob = visualisation_accuracy),
  draft_accuracy = sample(1:5, n, replace = TRUE, prob = draft_accuracy),
  writing_accuracy = sample(1:5, n, replace = TRUE, prob = writing_accuracy),
  editing_accuracy = sample(1:5, n, replace = TRUE, prob = editing_accuracy),
  translation_accuracy = sample(1:5, n, replace = TRUE, prob = translation_accuracy),
  summary_accuracy = sample(1:5, n, replace = TRUE, prob = summary_accuracy),
  admin_accuracy = sample(1:5, n, replace = TRUE, prob = admin_accuracy),
  impact_accuracy = sample(1:5, n, replace = TRUE, prob = impact_accuracy),
  commercilisation_accuracy = sample(1:5, n, replace = TRUE, prob = commercilisation_accuracy),
  other_accuracy = sample(1:5, n, replace = TRUE, prob = other_accuracy),
#########
  brainstorm_useful = sample(1:5, n, replace = TRUE, prob = brainstorm_useful),
  review_useful = sample(1:5, n, replace = TRUE, prob = review_useful),
  design_useful = sample(1:5, n, replace = TRUE, prob = design_useful),
  data_management_useful = sample(1:5, n, replace = TRUE, prob = data_management_useful),
  ethics_useful = sample(1:5, n, replace = TRUE, prob = ethics_useful),
  grant_useful = sample(1:5, n, replace = TRUE, prob = grant_useful),
  analysis_useful = sample(1:5, n, replace = TRUE, prob = analysis_useful),
  visualisation_useful = sample(1:5, n, replace = TRUE, prob = visualisation_useful),
  draft_useful = sample(1:5, n, replace = TRUE, prob = draft_useful),
  writing_useful = sample(1:5, n, replace = TRUE, prob = writing_useful),
  editing_useful = sample(1:5, n, replace = TRUE, prob = editing_useful),
  translation_useful = sample(1:5, n, replace = TRUE, prob = translation_useful),
  summary_useful = sample(1:5, n, replace = TRUE, prob = summary_useful),
  admin_useful = sample(1:5, n, replace = TRUE, prob = admin_useful),
  impact_useful = sample(1:5, n, replace = TRUE, prob = impact_useful),
  commercilisation_useful = sample(1:5, n, replace = TRUE, prob = commercilisation_useful),
  other_useful = sample(1:5, n, replace = TRUE, prob = other_useful),
  #########
  ############
  mental = sample(1:5, n, replace = TRUE, prob = probs_mental),
  time = sample(1:5, n, replace = TRUE, prob = probs_time),
  effort = sample(1:5, n, replace = TRUE, prob = probs_effort),
  stress = sample(1:5, n, replace = TRUE, prob = probs_stress),
  ###########
  trespass = sample(1:3, n, replace = TRUE, prob = probs_trespass),
  trespass_stages = sample(1:18, n, replace = TRUE, prob = probs_trespass_stages),
  brainstorm_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = brainstorm_trespass_accuracy),
  review_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = review_trespass_accuracy),
  design_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = design_trespass_accuracy),
  data_management_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = data_management_trespass_accuracy),
  ethics_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = ethics_trespass_accuracy),
  grant_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = grant_trespass_accuracy),
  analysis_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = analysis_trespass_accuracy),
  visualisation_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = visualisation_trespass_accuracy),
  draft_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = draft_trespass_accuracy),
  writing_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = writing_trespass_accuracy),
  editing_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = editing_trespass_accuracy),
  translation_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = translation_trespass_accuracy),
  summary_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = summary_trespass_accuracy),
  admin_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = admin_trespass_accuracy),
  impact_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = impact_trespass_accuracy),
  commercilisation_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = commercilisation_trespass_accuracy),
  other_trespass_accuracy = sample(1:5, n, replace = TRUE, prob = other_trespass_accuracy),
#########
  brainstorm_trespass_useful = sample(1:5, n, replace = TRUE, prob = brainstorm_trespass_useful),
  review_trespass_useful = sample(1:5, n, replace = TRUE, prob = review_trespass_useful),
  design_trespass_useful = sample(1:5, n, replace = TRUE, prob = design_trespass_useful),
  data_management_trespass_useful = sample(1:5, n, replace = TRUE, prob = data_management_trespass_useful),
  ethics_trespass_useful = sample(1:5, n, replace = TRUE, prob = ethics_trespass_useful),
  grant_trespass_useful = sample(1:5, n, replace = TRUE, prob = grant_trespass_useful),
  analysis_trespass_useful = sample(1:5, n, replace = TRUE, prob = analysis_trespass_useful),
  visualisation_trespass_useful = sample(1:5, n, replace = TRUE, prob = visualisation_trespass_useful),
  draft_trespass_useful = sample(1:5, n, replace = TRUE, prob = draft_trespass_useful),
  writing_trespass_useful = sample(1:5, n, replace = TRUE, prob = writing_trespass_useful),
  editing_trespass_useful = sample(1:5, n, replace = TRUE, prob = editing_trespass_useful),
  translation_trespass_useful = sample(1:5, n, replace = TRUE, prob = translation_trespass_useful),
  summary_trespass_useful = sample(1:5, n, replace = TRUE, prob = summary_trespass_useful),
  admin_trespass_useful = sample(1:5, n, replace = TRUE, prob = admin_trespass_useful),
  impact_trespass_useful = sample(1:5, n, replace = TRUE, prob = impact_trespass_useful),
  commercilisation_trespass_useful = sample(1:5, n, replace = TRUE, prob = commercilisation_trespass_useful),
  other_trespass_useful = sample(1:5, n, replace = TRUE, prob = other_trespass_useful),
  #########
  benefits = sample(1:8, n, replace = TRUE, prob = probs_benefits),
  risks = sample(1:9, n, replace = TRUE, prob = probs_risk),
  #########
  search = sample(1:5, n, replace = TRUE, prob = probs_search),
  method_understand = sample(1:5, n, replace = TRUE, prob = probs_method_understand),
  method_implement = sample(1:5, n, replace = TRUE, prob = probs_method_implement),
  method_troubleshoot = sample(1:5, n, replace = TRUE, prob = probs_method_troubleshoot),
  ###########
  search_likely = sample(1:5, n, replace = TRUE, prob = probs_search_likely),
  method_understand_likely = sample(1:5, n, replace = TRUE, prob = probs_method_understand_likely),
  method_implement_likely = sample(1:5, n, replace = TRUE, prob = probs_method_implement_likely),
  method_troubleshoot_likely = sample(1:5, n, replace = TRUE, prob = probs_method_troubleshoot_likely),
  ################
  use_learn = sample(1:5, n, replace = TRUE, prob = probs_use_learn),
  use_brainstorm = sample(1:5, n, replace = TRUE, prob = probs_use_brainstorm),
  use_review = sample(1:5, n, replace = TRUE, prob = probs_use_review),
  use_analysis = sample(1:5, n, replace = TRUE, prob = probs_use_analysis),
  use_write = sample(1:5, n, replace = TRUE, prob = probs_use_write),
  use_edit = sample(1:5, n, replace = TRUE, prob = probs_use_edit),
  #################
  use_learn_likely = sample(1:5, n, replace = TRUE, prob = probs_use_learn_likely),
  use_brainstorm_likely = sample(1:5, n, replace = TRUE, prob = probs_use_brainstorm_likely),
  use_review_likely = sample(1:5, n, replace = TRUE, prob = probs_use_review_likely),
  use_analysis_likely = sample(1:5, n, replace = TRUE, prob = probs_use_analysis_likely),
  use_write_likely = sample(1:5, n, replace = TRUE, prob = probs_use_write_likely),
  use_edit_likely = sample(1:5, n, replace = TRUE, prob = probs_use_edit_likely),
    #################
  institution = sample(1:3, n, replace = TRUE, prob = probs_institution),
  #############
  grant = sample(1:5, n, replace = TRUE, prob = probs_grant),
  grant_likely = sample(1:5, n, replace = TRUE, prob = probs_grant_likely),
  grant_impact = sample(1:5, n, replace = TRUE, prob = probs_grant_impact),
  disclosure = sample(1:11, n, replace = TRUE, prob = probs_disclosure),
  age = round(rnorm(n, mean = 33, sd = 12)),
  gender = sample(c("female",
                    "male",
                    "non-binary",
                    "prefer to self-describe",
                    "prefer not to say"), n, replace = TRUE,
                  prob = c(46.25, 46.25, 2.5, 2.5, 2.5)),
  experience = round(rnorm(n, mean = 7, sd = 3))
)
```

```{r}
lca <- sim_data %>% 
  dplyr::select(use_3_month,
     stages,
     benefits,
     risks,
      use_learn,
      use_brainstorm,
     use_review,
      use_analysis,
      use_write,
      use_edit,
      mental, 
      time,
      effort,
     stress
  ) %>%
  mutate(
    use_3_month = case_when(
      use_3_month == "Never"      ~ 1L,
      use_3_month == "Rarely"     ~ 2L,
      use_3_month == "Occassionally" ~ 3L,
      use_3_month == "Sometimes"  ~ 4L,
      use_3_month == "Often"      ~ 5L,
      use_3_month == "Very often" ~ 6L
    ),
    across(-use_3_month, as.integer)
  )

formula <- cbind(use_3_month,
     stages,
     benefits,
     risks,
      use_learn,
      use_brainstorm,
     use_review,
      use_analysis,
      use_write,
      use_edit,
      mental, 
      time,
      effort,
     stress) ~ 1

set.seed(123)

lca_1 <- poLCA(formula, lca, nclass = 1, nrep = 500, maxiter = 3000, verbose = FALSE)
lca_2 <- poLCA(formula, lca, nclass = 2, nrep = 500, maxiter = 3000, verbose = FALSE)
lca_3 <- poLCA(formula, lca, nclass = 3, nrep = 500, maxiter = 3000, verbose = FALSE)
lca_4 <- poLCA(formula, lca, nclass = 4, nrep = 500, maxiter = 3000, verbose = FALSE)
lca_5 <- poLCA(formula, lca, nclass = 5, nrep = 500, maxiter = 3000, verbose = FALSE)

fit_table <- data.frame(
  classes   = 1:5,
  AIC       = c(lca_1$aic, lca_2$aic, lca_3$aic, lca_4$aic, lca_5$aic),
  BIC       = c(lca_1$bic, lca_2$bic, lca_3$bic, lca_4$bic, lca_5$bic),
  log_lik   = c(lca_1$llik, lca_2$llik, lca_3$llik, lca_4$llik, lca_5$llik),
  n_params  = c(lca_1$npar, lca_2$npar, lca_3$npar, lca_4$npar, lca_5$npar)
)

entropy <- function(model) {
  probs <- model$posterior
  n <- nrow(probs)
  entropy_val <- 1 - (-sum(probs * log(probs + 1e-10))) / (n * log(ncol(probs)))
  return(round(entropy_val, 3))
}

fit_table$entropy <- c(
  NA, 
  entropy(lca_2),
  entropy(lca_3),
  entropy(lca_4),
  entropy(lca_5)
)

print(fit_table)

```

```{r}
best_model <- lca_3 # Update as needed
sim_data$class <- best_model$predclass

sim_data %>% 
  dplyr::select(class, where(is.numeric)) %>% 
  group_by(class) %>% 
  summarise(across(everything(),
                   list(mean = ~mean(.x, na.rm = TRUE),
                        sd = ~sd(.x, na.rm = TRUE)),
                   .names = "{.col}_{.fn}")) %>% 
  pivot_longer(-class,
               names_to = c("variable", "stat"),
               names_sep = "_(?=[^_]+$)") %>% 
  pivot_wider(names_from = c(class, stat),
              values_from = value)

#### Can ignore variables where mean does not make sense including 

######
```


```{r}
#### Code for tidySEM. Note in current version this is failing due to a possible
#set.seed(123)
#tidysem_lca <- mx_lca(data = lca, classes = 1:5)
B
#fit <- table_fit(tidysem_lca)
#print(fit)

#best_model <- tidysem_lca[[3]] update acorrding to best fitting model
#class_probs <- class_prob(best_model)
#print(class_probs)

#plot_lca(best_model)
```


```{r}
kruskal_data <- sim_data %>% 
  dplyr::select(!prim_field) %>% 
  dplyr::select(!role) %>% 
  dplyr::select(!gen_ai_tool) %>% 
  dplyr::select(!stages) %>% 
  dplyr::select(!use_3_month)

kruskal_vars <- names(dplyr::select(kruskal_data, -class))

kw_results <- kruskal_vars %>% 
  set_names() %>% 
  map(~kruskal.test(kruskal_data[[.x]] ~ kruskal_data$class)) %>% 
  map_dfr(~data.frame(
          chi_squared = round(.x$statistic, 3),
          df = .x$parameter,
          p_value = round(.x$p.value, 4)),
.id = "variable") %>% 
  mutate(
    p_adjusted = p.adjust(p_value, method = "bonferroni"),
    signficiant = p_value < 0.05,
    significant_adjusted = p_adjusted < 0.05
  )
  

sig_vars <- kw_results %>%
  filter(significant_adjusted == TRUE) %>%
  pull(variable)

posthoc_results <- sig_vars %>%
  set_names() %>%
  map(~dunn.test(kruskal_data[[.x]],
                 kruskal_data$class,
                 method = "bonferroni"))
```

```{r}
sim_data$class <- as.factor(sim_data$class)

model <- multinom(class ~ role + prim_field + age + experience + gender, data = sim_data)

summary(model)
```


\`\`
